# ====================================
# ClassifAI configuration file
# ====================================

[paths]

input_products_file = ./output/test_products_extracted_from_urls.csv
output_dir = ./output
output_file_name = prodotti_classificati_classifai
input_prodcom_2023_file = ./input/prodcom_2023_classification.csv

[qdrant]

qdrant_collection_name = prodcom_2023_flattened
# num matches da far elaborare a qdrant e poi presentare a openai
num_options_to_choose_from = 10

[openai]

openai_model = gpt-4o-mini
openai_embedding_model = text-embedding-3-large
default_openai_model_temperature = 0.0

[img]

img_temp_folder = ./img_temp
# passa direttamente l'url all'LLM
#image_passing_mode = 1
# salva img su disco, resize, passa img in base64 all'llm
image_passing_mode = 2
# gestisce img localmente senza file temporaneo, con Pillow per essere sicuri di passare sempre file png in uscita
#image_passing_mode = 3

[behaviour]

sleep_secs_between_products = 0.1

# Qdrant only
# classif_strategy = 1
# Qdrant then Openai
classif_strategy = 2
# Openai recursive on prodcom hierarchy
# classif_strategy = 3
# Openai recursive on prodcom hierarchy (NO generated description)
# classif_strategy = 4




